#!/usr/bin/env node
/**
 * Render an UFPel deliverable (HTML document or slide deck) to per-page PNGs
 * and optionally a PDF.
 *
 * Usage:
 *   node scripts/render.mjs <deliverable-dir | html-file> [options]
 *
 * The HTML is expected to contain one fixed-size element per page/slide:
 * any element matching `.page` (A4 documents) or `.slide` (16:9 decks).
 *
 * Options:
 *   --out <dir>     Output directory (default: <deliverable-dir>/out)
 *   --pdf           ALSO export <out>/deliverable.pdf via Chrome print
 *                   (template print CSS + @page rules control page size)
 *   --scale <n>     deviceScaleFactor for PNGs, e.g. 2 for retina (default: 1)
 *   --only <n[,m]>  Render only these 1-based page numbers (fast iteration)
 *   --debug         ALSO write page-NN.debug.png per page: coordinate grid +
 *                   a labeled content box for every [data-asset] element, and
 *                   out/layout.json with exact boxes, pairwise overlaps and
 *                   OVERFLOW flags (content escaping its fixed page box).
 *                   Give a vision model BOTH images per page: the clean one to
 *                   judge look/brand, the debug one to reason in pixels.
 *
 * Overlap notes:
 *   - computed on CONTENT boxes: alpha-trimmed visible pixels for <img>
 *     assets, CSS border box for text/blocks
 *   - ancestor/descendant pairs are skipped (nesting is composition, not
 *     collision); only sibling overlaps are reported
 *
 * Overflow notes (the #1 document defect):
 *   - page.scrollHeight > page.clientHeight  → content flowed past the page
 *   - any element (tagged or not) whose box crosses the page bounds is
 *     reported with a text snippet so you can find it
 */
import { chromium } from 'playwright';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

/**
 * If the deliverable has a pages/ folder, assemble index.html from it:
 * head.html + styles.css link + every pages/NN-*.html fragment in filename
 * order (one fragment = one page/slide = one PDF page). index.html is a
 * BUILD ARTIFACT — author the fragments, never the assembled file.
 */
async function assemble(dir) {
  const pagesDir = path.join(dir, 'pages');
  if (!existsSync(pagesDir)) return null;
  const fragments = (await readdir(pagesDir))
    .filter((f) => f.endsWith('.html'))
    .sort();
  if (fragments.length === 0) return null;
  const head = existsSync(path.join(dir, 'head.html'))
    ? await readFile(path.join(dir, 'head.html'), 'utf8')
    : '<meta charset="utf-8">\n<link rel="stylesheet" href="styles.css">';
  const bodies = [];
  for (const f of fragments) {
    bodies.push(await readFile(path.join(pagesDir, f), 'utf8'));
  }
  const html =
    '<!-- GENERATED by render.mjs from pages/*.html — DO NOT EDIT.\n' +
    '     Edit the fragments in pages/ instead; this file is rebuilt on every render. -->\n' +
    `<!doctype html>\n<html lang="en">\n<head>\n${head.trim()}\n</head>\n<body>\n\n` +
    bodies.map((b) => b.trim()).join('\n\n') +
    '\n\n</body>\n</html>\n';
  const indexPath = path.join(dir, 'index.html');
  await writeFile(indexPath, html);
  return indexPath;
}

const BOOLEAN_FLAGS = new Set(['pdf', 'debug']);

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const name = a.slice(2);
      if (BOOLEAN_FLAGS.has(name)) args[name] = true;
      else args[name] = argv[++i];
    } else args._.push(a);
  }
  return args;
}

async function launchBrowser() {
  // --allow-file-access-from-files lets the annotator read <img> pixels
  // (canvas getImageData) on file:// pages without tainted-canvas errors.
  // --force-color-profile=srgb keeps PDF colors identical to the PNGs: on
  // wide-gamut displays Chrome otherwise converts through the display
  // profile when printing, visibly shifting the brand blue in the PDF.
  const launchArgs = ['--allow-file-access-from-files', '--force-color-profile=srgb'];
  for (const opts of [{ channel: 'chrome' }, {}, { channel: 'msedge' }]) {
    try {
      return await chromium.launch({ ...opts, args: launchArgs });
    } catch (err) {
      if (opts.channel === 'msedge') {
        throw new Error(
          `No browser available. Install one with: npx playwright install chromium\n(${err.message})`,
        );
      }
    }
  }
}

/**
 * Runs inside the page, once per page/slide element (identified by index in
 * the `.page, .slide` node list). Appends a grid + labeled content-box
 * overlay INSIDE the page element and returns the boxes in PAGE-LOCAL
 * coordinates, plus overflow diagnostics.
 */
function annotatePage(pageIndex) {
  // tooling-only hues, deliberately outside the brand palette
  const COLORS = ['#00C2E0', '#00FF6A', '#FFB800', '#FF3B30', '#C4FF00', '#B26BFF', '#FF8A00'];
  const THRESHOLDS = { glow: 128 };
  const DEFAULT_THRESHOLD = 10;

  const pageEl = document.querySelectorAll('.page, .slide')[pageIndex];
  const pageRect = pageEl.getBoundingClientRect();
  if (getComputedStyle(pageEl).position === 'static') {
    pageEl.style.position = 'relative';
  }

  function naturalContentBox(el) {
    if (el.tagName !== 'IMG' || !el.naturalWidth) return null;
    const threshold = THRESHOLDS[el.dataset.profile] ?? DEFAULT_THRESHOLD;
    try {
      const c = document.createElement('canvas');
      c.width = el.naturalWidth;
      c.height = el.naturalHeight;
      const ctx = c.getContext('2d', { willReadFrequently: true });
      ctx.drawImage(el, 0, 0);
      const d = ctx.getImageData(0, 0, c.width, c.height).data;
      let minX = c.width, minY = c.height, maxX = -1, maxY = -1;
      for (let y = 0; y < c.height; y++) {
        for (let x = 0; x < c.width; x++) {
          if (d[(y * c.width + x) * 4 + 3] >= threshold) {
            if (x < minX) minX = x;
            if (x > maxX) maxX = x;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
          }
        }
      }
      return maxX < 0 ? null : { minX, minY, maxX, maxY };
    } catch {
      return null;
    }
  }

  const round = (b) => ({
    x: Math.round(b.x),
    y: Math.round(b.y),
    width: Math.round(b.width),
    height: Math.round(b.height),
  });
  const toLocal = (r) => ({
    x: r.x - pageRect.x,
    y: r.y - pageRect.y,
    width: r.width,
    height: r.height,
  });

  const overlay = document.createElement('div');
  overlay.className = 'ufpel-debug-overlay';
  overlay.style.cssText =
    'position:absolute;inset:0;z-index:99999;pointer-events:none;font-family:monospace;';

  // grid: fine line every 50px, strong line + edge label every 200px
  const grid = document.createElement('div');
  grid.style.cssText =
    'position:absolute;inset:0;' +
    'background-image:' +
    'linear-gradient(to right, rgba(0,194,224,.5) 1px, transparent 1px),' +
    'linear-gradient(to bottom, rgba(0,194,224,.5) 1px, transparent 1px),' +
    'linear-gradient(to right, rgba(0,194,224,.16) 1px, transparent 1px),' +
    'linear-gradient(to bottom, rgba(0,194,224,.16) 1px, transparent 1px);' +
    'background-size:200px 200px,200px 200px,50px 50px,50px 50px;';
  overlay.appendChild(grid);

  const W = pageRect.width, H = pageRect.height;
  for (let x = 200; x < W; x += 200) {
    const t = document.createElement('div');
    t.textContent = String(x);
    t.style.cssText =
      `position:absolute;left:${x + 3}px;top:2px;font-size:14px;` +
      'color:#00C2E0;text-shadow:0 0 3px #000,0 0 3px #000;';
    overlay.appendChild(t);
  }
  for (let y = 200; y < H; y += 200) {
    const t = document.createElement('div');
    t.textContent = String(y);
    t.style.cssText =
      `position:absolute;left:3px;top:${y + 2}px;font-size:14px;` +
      'color:#00C2E0;text-shadow:0 0 3px #000,0 0 3px #000;';
    overlay.appendChild(t);
  }

  const boxes = [];
  const els = Array.from(pageEl.querySelectorAll('[data-asset]'));
  els.forEach((el, i) => {
    const r = el.getBoundingClientRect();
    const color = COLORS[i % COLORS.length];
    const id = el.getAttribute('data-asset');
    const nat = naturalContentBox(el);
    let visible = toLocal(r);
    let trimmed = false;
    if (nat) {
      const sx = r.width / el.naturalWidth;
      const sy = r.height / el.naturalHeight;
      visible = {
        x: r.x - pageRect.x + nat.minX * sx,
        y: r.y - pageRect.y + nat.minY * sy,
        width: (nat.maxX - nat.minX + 1) * sx,
        height: (nat.maxY - nat.minY + 1) * sy,
      };
      trimmed = true;
    }

    boxes.push({
      id,
      profile: el.dataset.profile ?? null,
      // `content` = visible pixels (reason with this);
      // `element` = CSS border box (position with this)
      content: round(visible),
      element: round(toLocal(r)),
      trimmed,
      _isDescendantOf: els
        .map((other, j) => (other !== el && other.contains(el) ? j : -1))
        .filter((j) => j >= 0),
    });

    if (trimmed) {
      const elBox = document.createElement('div');
      const lr = toLocal(r);
      elBox.style.cssText =
        `position:absolute;left:${lr.x}px;top:${lr.y}px;width:${lr.width}px;height:${lr.height}px;` +
        'border:1px solid rgba(0,0,0,.35);box-sizing:border-box;';
      overlay.appendChild(elBox);
    }

    const box = document.createElement('div');
    box.style.cssText =
      `position:absolute;left:${visible.x}px;top:${visible.y}px;` +
      `width:${visible.width}px;height:${visible.height}px;` +
      `border:3px dashed ${color};box-sizing:border-box;`;
    overlay.appendChild(box);

    const v = round(visible);
    const label = document.createElement('div');
    label.textContent = `${id} ${v.x},${v.y} ${v.width}×${v.height}`;
    const labelY = visible.y >= 24 ? visible.y - 24 : visible.y + 2;
    label.style.cssText =
      `position:absolute;left:${Math.max(0, visible.x)}px;top:${labelY}px;` +
      `background:${color};color:#000;font-size:16px;font-weight:bold;` +
      'padding:1px 8px;white-space:nowrap;z-index:100000;';
    overlay.appendChild(label);
  });

  // ---- overflow diagnostics -------------------------------------------
  const overflow = {
    pageScroll:
      pageEl.scrollHeight > pageEl.clientHeight + 1 ||
      pageEl.scrollWidth > pageEl.clientWidth + 1
        ? {
            scrollHeight: pageEl.scrollHeight,
            clientHeight: pageEl.clientHeight,
            scrollWidth: pageEl.scrollWidth,
            clientWidth: pageEl.clientWidth,
          }
        : null,
    escapes: [],
  };
  // deepest elements whose visible box crosses the page bounds
  const all = pageEl.querySelectorAll('*');
  const offenders = [];
  for (const el of all) {
    if (el.closest('.ufpel-debug-overlay')) continue;
    if (!el.offsetHeight && !el.offsetWidth) continue;
    const r = el.getBoundingClientRect();
    const over =
      r.bottom > pageRect.bottom + 1 ||
      r.top < pageRect.top - 1 ||
      r.right > pageRect.right + 1 ||
      r.left < pageRect.left - 1;
    if (over) offenders.push(el);
  }
  const deepest = offenders.filter((el) => !offenders.some((o) => o !== el && el.contains(o)));
  for (const el of deepest.slice(0, 5)) {
    const r = el.getBoundingClientRect();
    overflow.escapes.push({
      tag: el.tagName.toLowerCase(),
      class: el.className && typeof el.className === 'string' ? el.className : null,
      asset: el.closest('[data-asset]')?.getAttribute('data-asset') ?? null,
      box: round(toLocal(r)),
      text: (el.textContent || '').trim().slice(0, 60) || null,
    });
  }

  pageEl.appendChild(overlay);
  return { boxes, overflow, size: { width: Math.round(W), height: Math.round(H) } };
}

function removeOverlays() {
  document.querySelectorAll('.ufpel-debug-overlay').forEach((el) => el.remove());
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const target = args._[0];
  if (!target) {
    console.error(
      'Usage: node scripts/render.mjs <deliverable-dir | html-file> [--debug] [--pdf] [--scale n] [--only 1,3]',
    );
    process.exit(1);
  }

  const targetPath = path.resolve(target);
  let htmlPath = targetPath;
  let baseDir = path.dirname(targetPath);
  if (statSync(targetPath).isDirectory()) {
    baseDir = targetPath;
    htmlPath = (await assemble(baseDir)) ?? path.join(baseDir, 'index.html');
  }

  const outDir = path.resolve(args.out ?? path.join(baseDir, 'out'));
  await mkdir(outDir, { recursive: true });
  const scale = Number(args.scale ?? 1);
  const only = args.only
    ? new Set(args.only.split(',').map((n) => Number(n.trim())))
    : null;

  const browser = await launchBrowser();
  try {
    const page = await browser.newPage({
      viewport: { width: 1600, height: 1200 },
      deviceScaleFactor: scale,
    });
    await page.goto(pathToFileURL(htmlPath).href, { waitUntil: 'networkidle' });
    await page.evaluate(() => document.fonts.ready);
    // Templates that draw async content (Chart.js canvases) expose a promise;
    // wait for it so screenshots capture the final state.
    await page.evaluate(() => window.__ufpelReady ?? null);
    await page.waitForTimeout(50);

    const pageCount = await page.evaluate(
      () => document.querySelectorAll('.page, .slide').length,
    );
    if (pageCount === 0) {
      throw new Error('No .page or .slide elements found in the document.');
    }

    const result = { ok: true, out: outDir, pages: pageCount, rendered: [] };
    const pad = (n) => String(n).padStart(2, '0');
    const locator = page.locator('.page, .slide');

    // 1) clean shots for every requested page
    for (let i = 0; i < pageCount; i++) {
      if (only && !only.has(i + 1)) continue;
      const file = path.join(outDir, `page-${pad(i + 1)}.png`);
      await locator.nth(i).screenshot({ path: file });
      result.rendered.push(path.basename(file));
    }

    // 2) debug pass: annotate page-by-page, shoot, collect layout
    if (args.debug) {
      const layout = { pages: [] };
      for (let i = 0; i < pageCount; i++) {
        if (only && !only.has(i + 1)) continue;
        const info = await page.evaluate(annotatePage, i);
        const file = path.join(outDir, `page-${pad(i + 1)}.debug.png`);
        await locator.nth(i).screenshot({ path: file });
        await page.evaluate(removeOverlays);

        // sibling-only pairwise overlaps on content boxes
        const overlaps = [];
        const b = info.boxes;
        for (let x = 0; x < b.length; x++) {
          for (let y = x + 1; y < b.length; y++) {
            if (b[x]._isDescendantOf.includes(y) || b[y]._isDescendantOf.includes(x)) continue;
            const A = b[x].content, B = b[y].content;
            const w = Math.min(A.x + A.width, B.x + B.width) - Math.max(A.x, B.x);
            const h = Math.min(A.y + A.height, B.y + B.height) - Math.max(A.y, B.y);
            if (w > 0 && h > 0) {
              overlaps.push({ a: b[x].id, b: b[y].id, width: Math.round(w), height: Math.round(h) });
            }
          }
        }
        for (const box of b) delete box._isDescendantOf;

        layout.pages.push({
          page: i + 1,
          size: info.size,
          boxes: info.boxes,
          overlaps,
          overflow: info.overflow,
        });
        result.rendered.push(path.basename(file));
      }
      const layoutPath = path.join(outDir, 'layout.json');
      await writeFile(layoutPath, JSON.stringify(layout, null, 2));
      result.layout = layoutPath;
      result.problems = layout.pages
        .filter((p) => p.overlaps.length || p.overflow.pageScroll || p.overflow.escapes.length)
        .map((p) => ({
          page: p.page,
          overlaps: p.overlaps.length,
          overflow: Boolean(p.overflow.pageScroll) || p.overflow.escapes.length > 0,
        }));
    }

    // 3) PDF export — assembled FROM page renders, not Chrome's print
    // layout path. Printing the live DOM shifts colors and mangles
    // transforms/transparency differently per PDF viewer; embedding the
    // validated renders guarantees the PDF looks exactly like the PNGs
    // in every viewer. Renders are taken at --pdf-scale (default 2) so
    // the embedded images are print-crisp.
    if (args.pdf) {
      const pdfScale = Number(args['pdf-scale'] ?? 2);
      const pdfSrcDir = path.join(outDir, 'pdf-src');
      await mkdir(pdfSrcDir, { recursive: true });

      const hiPage = await browser.newPage({
        viewport: { width: 1600, height: 1200 },
        deviceScaleFactor: pdfScale,
      });
      await hiPage.goto(pathToFileURL(htmlPath).href, { waitUntil: 'networkidle' });
      await hiPage.evaluate(() => document.fonts.ready);
      await hiPage.evaluate(() => window.__ufpelReady ?? null);
      await hiPage.waitForTimeout(50);

      const size = await hiPage.evaluate(() => {
        const r = document.querySelector('.page, .slide').getBoundingClientRect();
        return { width: r.width, height: r.height };
      });
      const hiLocator = hiPage.locator('.page, .slide');
      const srcFiles = [];
      for (let i = 0; i < pageCount; i++) {
        const file = path.join(pdfSrcDir, `page-${pad(i + 1)}.png`);
        await hiLocator.nth(i).screenshot({ path: file });
        srcFiles.push(file);
      }
      await hiPage.close();

      const wrapperPath = path.join(pdfSrcDir, 'pdf.html');
      await writeFile(
        wrapperPath,
        `<!doctype html><html><head><style>
           * { margin: 0; padding: 0; }
           @page { size: ${size.width}px ${size.height}px; margin: 0; }
           img { display: block; width: ${size.width}px; height: ${size.height}px; page-break-after: always; }
         </style></head><body>` +
          srcFiles.map((f) => `<img src="${pathToFileURL(f).href}">`).join('') +
          '</body></html>',
      );

      const pdfPage = await browser.newPage();
      await pdfPage.goto(pathToFileURL(wrapperPath).href, { waitUntil: 'networkidle' });
      const pdfPath = path.join(outDir, 'deliverable.pdf');
      await pdfPage.pdf({ path: pdfPath, preferCSSPageSize: true, printBackground: true });
      await pdfPage.close();
      await rm(pdfSrcDir, { recursive: true, force: true });
      result.pdf = pdfPath;
    }

    console.log(JSON.stringify(result, null, 2));
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
